server:
  grpc:
    host: "0.0.0.0"
    port: 50051
    max_connection_age: "30s"
    max_connection_age_grace: "5s"

  shutdown_timeout: "15s"

sentry:
  dsn: "your_sentry_dsn"
  environment: "production"  # или "development"

logging:
  host: "0.0.0.0"
  port: 9091